### ISSUE TITLE
Check client state for project

### ISSUE THREAD

**Issue by eliasson** [quarterapp/quarterapp#21]
When a client state is decreased (set to inactive, or to archived) this change should be cascading for any project associated with that client.

Should the properties of Project instances be changed, or should the query to retrieve active projects be altered? It will be weird if a project has state active, but the client is inactive or archived.

Also, controls should be made to not allow invalid state changes:
- Settinga project active when client is inactive / archived should not be allowed
- Creating new projects for archived clients should not be allowed.

@dbackman do you agree on this lifecycle management?

And the same reasoning goes for Project -> Activity

**Comment by dbackman** [comment]
@eliasson Yes, lets try it out!

**Comment by eliasson** [comment]
After discussions, lets go with the other way - changing the filters and queries to not include objects from inactive / archived parents.

The reason is that we should not alter state on users objects, and this solution also allows for changing back from inactive to active again, keeping all children state intact.
